name: "CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: yarn --frozen-lockfile

      - name: "Test"
        run: yarn test

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: true

  dependabot-merge:
    name: "Dependabot automerge"
    runs-on: ubuntu-latest
    needs: [ "test" ]
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
